### ISSUE TITLE
problemi con CSS riusando https://github.com/atorin/documento-starter-kit-docs-italia

### ISSUE THREAD

**Issue by cirospat** [atorin/documento-starter-kit-docs-italia#1]
salve
ho riusato: https://github.com/atorin/documento-starter-kit-docs-italia
per creare questo progetto su Read the Docs:
http://linee-guida-open-data-comune-palermo.readthedocs.io

Ma ho notato che in basso a sinistra c'è una cattiva formattazione dove si trovano i link al download di PDF, HTMLZIP e EPUB.

Qui sotto lo screenshot

![image](https://user-images.githubusercontent.com/3757525/37375286-288a352e-271f-11e8-8196-5fe154b17318.png)

In cosa sbaglio?

Grazie

**Comment by alterat** [comment]
Buongiorno Ciro! Grazie per la segnalazione.

Questo mio repo personale aveva ancora il vecchio stile CSS con il bug, ho provveduto a correggere l'errore. 

Per ogni aggiornamento futuro, puoi fare riferimento al repo ufficiale dello starter kit sull'account Italia: https://github.com/italia/docs-italia-starter-kit/tree/master/repo-documento

**Comment by cirospat** [comment]
grazie

era qui il problemino:

![image](https://user-images.githubusercontent.com/3757525/37394401-f537fd8c-2773-11e8-9879-8c8263c44f52.png)

ora ho corretto e funziona
Grazie molto

**Comment by alterat** [comment]
Sì esatto, si trattava di una versione precedente del conf.py che conteneva ancora l'errore. 

Mi fa piacere che tutto funzioni correttamente ora! :)

**Comment by cirospat** [comment]
grazie
così proseguo nel lavoro di inserimento contenuti nei file .rst
Appena finisco ve lo comunico (linee guida open data comune Palermo)
buon lavoro
